#!/bin/bash

# iKeep v.2.0.0
# Copyright (c) 2024 Leonard Wu <leonard.wu92@alumni.ic.ac.uk>
# https://github.com/leonardw/ikeep
# MIT Licensed
cmdargs=$@

appname=iKeep
appver=2.0.0
copyyr=2024
homeurl="https://github.com/leonardw/ikeep"

profiledir=$HOME/Library/Application\ Support/$appname/Chrome
firstrun="$profiledir/First Run"
runprefix="$profiledir/firstrun-"
versionrun="${runprefix}${appname}-$appver"
app="$(dirname "$0")/../.."

SEARCH_DIRS="${HOME}/Applications/:/Applications/:${app}/../"
SEARCH_BINS="Chromium.app/Contents/MacOS/Chromium:Google Chrome.app/Contents/MacOS/Google Chrome"

findChrome() {
	local IFS=':'
	local chromebin=""
	for dir in ${SEARCH_DIRS}; do
		for bin in ${SEARCH_BINS}; do
			if [[ -e "$dir$bin" ]]; then
				chromebin="$dir$bin"
				break 2
			fi
		done
	done
	if [[ "$chromebin" == "" ]]; then
		for bin in ${SEARCH_BINS}; do
			local binfile=$(basename "$bin")
			chromebin=$(which "$binfile")
			[[ -n "$chromebin" ]] && break
		done
	fi
	echo "$chromebin"
}

popalert() {
out=$(osascript <<EOT
	tell application "System Events"
		display alert "$1"
	end tell
EOT)
return 0
}

# Find Chrome runtime
chrome=$(findChrome)

# Quit if Chrome is not found
if [[ "$chrome" == "" ]]
then
	$(popalert "$appname $appver\n\nChrome browser not found!\n\niKeeper requires Chrome browser to function. Please install Google Chrome, Chromium or Chromium Legacy, then retry again.")
	exit 1
fi

# Remove if profile dir already used by something else
if [[ -e "$profiledir" ]] && [[ -h "$profiledir" || ! -d "$profiledir" ]]
then
	rm -fr "$profiledir"
fi
# Create profile dir if none exist
if [[ ! -e "$profiledir" ]]
then
	mkdir -p "$profiledir"
	touch "$firstrun"
fi
# First run, show version info
if [[ ! -e "$versionrun" ]]
then
	#rm -f "${runprefix}*"
	touch "$versionrun"
	$(popalert "$appname $appver\n\nMIT Licensed\nCopyright (c) $copyyr Leonard Wu\n$homeurl")
fi

exec "$chrome" --no-default-browser-check --app="https://keep.google.com" --user-data-dir="$profiledir" $cmdargs
